implement lex for mod assignments

diff --git a/test/run b/test/run
--- a/test/run
+++ b/test/run
@@ -63,6 +63,28 @@ err2=$?
 
 err=$((err+err1+err2))
 
+# EXTERNAL INITIALIZATION ONLY
+
+gcc -std=c2x ../main.c ../tokenizer.c -o ./generator
+res=$(./generator ./ext_init_only.ned 2>&1)
+
+init_line=$(cat <<EOF
+TOKEN_INDENT(\s\s\s\s)
+TOKEN_INDENT(\s\s\s\s)
+TOKEN_NUMBER(1)
+TOKEN_EXTERNAL_MODULE(print)
+EOF
+)
+
+init_snippet=$(echo "$res" | tail -23 | head -4)
+if [[ "$init_snippet" == "$init_line" ]]; then
+    err1=0
+else
+    err1=1
+fi
+
+err=$((err+err1))
+
 # NON-EXTERNAL BOOLEAN TEST VARIATIONS
 # \t \t {varchain}
 # \t \t !{varchain}
@@ -94,6 +116,72 @@ res=$(./generator ./decr_op.ned 2>&1)
 echo "$res" | grep -q "TOKEN_DECREMENT(--)"
 err1=$?
 echo "$res" | grep -q "TOKEN_NUMBER(2)"
+err2=$?
+
+err=$((err+err1+err2))
+
+# STR ASSIGNMENT TEST
+
+gcc -std=c2x ../main.c ../tokenizer.c -o ./generator
+# ./generator ./assign_str.ned 2>&1
+res=$(./generator ./assign_str.ned 2>&1)
+echo "$res" | grep -q "TOKEN_VARIABLE_IDENTIFIER(str)"
+err1=$?
+echo "$res" | grep -q "TOKEN_EQUALS(=)"
+err2=$?
+echo "$res" | grep -q "TOKEN_STRING(test1)"
+err3=$?
+echo "$res" | grep -q "TOKEN_STRING(test2)"
+err4=$?
+echo "$res" | grep -q "TOKEN_INVALID"
+if [[ $? -eq 0 ]]; then
+    err5=1 # invert grep q (should not match invalid)
+else
+    err5=0
+fi
+
+err=$((err+err1+err2+err3+err4+err5))
+
+# MOD VAR ASSIGNMENT TEST
+
+gcc -std=c2x ../main.c ../tokenizer.c -o ./generator
+# ./generator ./assign_mod.ned 2>&1
+res=$(./generator ./assign_mod.ned 2>&1)
+
+# \t \t m2.str = m1.str
+assignment=$(cat<<EOF
+TOKEN_INDENT(\s\s\s\s)
+TOKEN_INDENT(\s\s\s\s)
+TOKEN_MODULE_IDENTIFIER(m2)
+TOKEN_DOT(.)
+TOKEN_VARIABLE_IDENTIFIER(str)
+TOKEN_SPACE( )
+TOKEN_EQUALS(=)
+TOKEN_SPACE( )
+TOKEN_MODULE_IDENTIFIER(m1)
+TOKEN_DOT(.)
+TOKEN_VARIABLE_IDENTIFIER(str)
+EOF
+)
+
+output_snippet=$(echo "$res" | tail -15 | head -11)
+
+if [[ "$output_snippet" == "$assignment" ]]; then
+    err1=0
+else
+    err1=1
+fi
+err=$((err+err1))
+
+# ASSIGN EXTERN MOD
+
+gcc -std=c2x ../main.c ../tokenizer.c -o ./generator
+# ./generator ./assign_ext_mod.ned 2>&1
+res=$(./generator ./assign_ext_mod.ned 2>&1)
+
+echo "$res" | grep -q "TOKEN_EXTERNAL_MODULE(ext_mod)"
+err1=$?
+echo "$res" | grep -q "TOKEN_TEXT"  # comment
 err2=$?
 
 err=$((err+err1+err2))
